name: Local CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "✅ Workflow is running on GitHub!"

      - name: List project files
        run: ls -l
